### ISSUE TITLE
Error installing  vocsy_epub_viewer in iOS

### ISSUE THREAD

**Issue by medelmendoza** [kaushikgodhani/vocsy_epub_viewer#27]
Hello, tried this library and works correctly in android. But when trying to run this in iOS, it always prompt an error with this log : 

Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `path_provider_foundation` from `.symlinks/plugins/path_provider_foundation/ios`
    -> Fetching podspec for `vocsy_epub_viewer` from `.symlinks/plugins/vocsy_epub_viewer/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_7_f.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/7/f/EpubViewerKit/0.1.3/EpubViewerKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/7/f/EpubViewerKit/0.1.3/EpubViewerKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_2_1_2.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/1/2/SSZipArchive/2.5.3/SSZipArchive.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_e_4.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/e/4/MenuItemKit/4.0.1/MenuItemKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_2_e.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/2/e/ZFDragableModalTransition/0.6/ZFDragableModalTransition.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_2_e_0.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/e/0/AEXML/4.6.1/AEXML.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_9_d_3.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/9/d/3/FontBlaster/5.3.0/FontBlaster.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_9_4_5.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/9/4/5/RealmSwift/10.35.1/RealmSwift.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/1/2/SSZipArchive/2.2.3/SSZipArchive.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/e/4/MenuItemKit/4.0.1/MenuItemKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/2/e/ZFDragableModalTransition/0.6/ZFDragableModalTransition.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/e/0/AEXML/4.6.0/AEXML.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/9/d/3/FontBlaster/5.1.1/FontBlaster.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/9/4/5/RealmSwift/5.5.1/RealmSwift.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_b_a_7.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/a/7/Realm/10.35.1/Realm.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/a/7/Realm/5.5.1/Realm.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/a/7/Realm/5.5.1/Realm.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.10.2/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.5/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.2.2/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.22.4/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.17.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.12.1303/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.9.102/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
    Comparing resolved specification to the sandbox manifest
      A AEXML
      A EpubViewerKit
      A Flutter
      A FontBlaster
      A MenuItemKit
      A Realm
      A RealmSwift
      A SSZipArchive
      A ZFDragableModalTransition
      A path_provider_foundation
      A vocsy_epub_viewer
    Downloading dependencies
    -> Installing AEXML (4.6.0)
      > Copying AEXML from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/AEXML/4.6.0-2fbb7` to `Pods/AEXML`
    -> Installing EpubViewerKit (0.1.3)
      > Copying EpubViewerKit from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/EpubViewerKit/0.1.3-5f6c8` to `Pods/EpubViewerKit`
    -> Installing Flutter (1.0.0)
    -> Installing FontBlaster (5.1.1)
      > Copying FontBlaster from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/FontBlaster/5.1.1-8897e` to `Pods/FontBlaster`
    -> Installing MenuItemKit (4.0.1)
      $ /usr/bin/git ls-remote -- https://github.com/cxa/MenuItemKit.git master
      22c027e9cdd89a8e449c714b5a5f64c8976b54ac	refs/heads/master
      > Copying MenuItemKit from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/MenuItemKit/4.0.1-14599` to `Pods/MenuItemKit`
    -> Installing Realm (5.5.1)
      > Copying Realm from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/Realm/5.5.1-c2ffe` to `Pods/Realm`
    -> Installing RealmSwift (5.5.1)
      > Copying RealmSwift from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/RealmSwift/5.5.1-5a35c` to `Pods/RealmSwift`
    -> Installing SSZipArchive (2.2.3)
      > Copying SSZipArchive from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/SSZipArchive/2.2.3-62d49` to `Pods/SSZipArchive`
    -> Installing ZFDragableModalTransition (0.6)
      > Copying ZFDragableModalTransition from `/Users/btsolve/Library/Caches/CocoaPods/Pods/Release/ZFDragableModalTransition/0.6-0d294` to `Pods/ZFDragableModalTransition`
    -> Installing path_provider_foundation (0.0.1)
    -> Installing vocsy_epub_viewer (2.0.0)
      - Running pre install hooks
      - Running pre integrate hooks
    Generating Pods project
      - Creating Pods project
      - Installing files into Pods project
        - Adding source files
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    ### Command
    ```
    /usr/local/bin/pod install --verbose
    ```
    ### Report
    * What did you do?
    * What did you expect to happen?
    * What happened instead?
    ### Stack
    ```
       CocoaPods : 1.11.3
            Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
        RubyGems : 3.0.3.1
            Host : macOS 12.6 (21G115)
           Xcode : 14.1 (14B47b)
             Git : git version 2.37.1 (Apple Git-137.1)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```
    ### Plugins
    ```
    cocoapods-deintegrate : 1.0.5
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.1
    cocoapods-trunk       : 1.6.0
    cocoapods-try         : 1.2.0
    ```
    ### Podfile
    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '11.0'
    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'
    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }
    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end
      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
    end
    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
    flutter_ios_podfile_setup
    target 'Runner' do
      use_frameworks!
      use_modular_headers!
      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
    end
    ```
    ### Error
    ```
    Errno::ENOENT - No such file or directory @ realpath_rec - /Users/btsolve/development/playground/sample_epub/ios/Pods/Realm/Realm/RLMAccessor.h
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/project.rb:326:in `realpath'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/project.rb:326:in `realpath'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/project.rb:326:in `reference_for_path'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/project.rb:269:in `add_file_reference'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:228:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:227:in `map'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:227:in `block in add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:217:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:217:in `flat_map'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:217:in `add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:99:in `block in add_source_files_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:98:in `add_source_files_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:49:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:102:in `block in install_file_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:100:in `install_file_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:301:in `generate_pods_project'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:180:in `integrate'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:167:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```
    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    [!] Oh no, an error occurred.
    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+realpath_rec+-+%2FUsers%2Fbtsolve%2Fdevelopment%2Fplayground%2Fsample_epub%2Fios%2FPods%2FRealm%2FRealm%2FRLMAccessor.h&type=Issues
    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new
    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
    Don't forget to anonymize any private data!
    Looking for related issues on cocoapods/cocoapods...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/cocoapods/cocoapods/issues/new
Error running pod install
Error launching application on iPhone 14 Pro Max.
Exited

I hope somebody could help me with this. Thank you

P.S This project was newly created so no other library is associated with my pubspec.yaml file (just to try this library before putting in my project)

**Comment by medelmendoza** [comment]
Just follow the solution in this link if you will also encounter this issue

https://github.com/realm/realm-swift/issues/6407
