### ISSUE TITLE
Facing Issue To Calling Epub and App is crashed

### ISSUE THREAD

**Issue by hozefamakhariya** [kaushikgodhani/vocsy_epub_viewer#32]
Process: com.raaymedia.saga.ebooks, PID: 6586
E/AndroidRuntime( 6586): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.raaymedia.saga.ebooks/com.folioreader.ui.activity.FolioActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
E/AndroidRuntime( 6586):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/AndroidRuntime( 6586):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime( 6586):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime( 6586):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6586):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6586):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime( 6586):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6586):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6586):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6586):        at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime( 6586):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6586):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6586):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 6586): Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
E/AndroidRuntime( 6586):        at com.folioreader.Config.<init>(Config.java:160)
E/AndroidRuntime( 6586):        at com.folioreader.util.AppUtil$Companion.getSavedConfig(AppUtil.kt:120)
E/AndroidRuntime( 6586):        at com.folioreader.ui.activity.FolioActivity.setConfig(FolioActivity.kt:1129)
E/AndroidRuntime( 6586):        at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:273)
E/AndroidRuntime( 6586):        at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime( 6586):        at android.app.Activity.performCreate(Activity.java:8269)
E/AndroidRuntime( 6586):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime( 6586):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)

**Comment by hozefamakhariya** [comment]
It was emulator issue

**Comment by hozefamakhariya** [comment]
It was emulator issue
